---
- name: Playbook to provision azure resources
  hosts: localhost
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible-rhel-rg
        location: westeurope

    - name: Create virtual network
      azure_rm_virtualnetwork:
       name: ansible-rhel-vnet
       resource_group: ansible-rhel-rg
       address_prefixes_cidr: 
           - "10.1.0.0/16"

   - name: Add subnet
     azure_rm_subnet:
       name: ansible-rhel-vnet
       resource_group: ansible-rhel-rg
       virtual_network_name: ansible-rhel-vnet
       address_prefixes_cidr: 
           - "10.1.0.0/24"
      

   - name: Create public ip
     azure_rm_publicipaddress:
       name: ansible-rhel-ip
       resource_group: ansible-rhel-rg
       allocation_method: Static
       register: ansible-rhel-ip
       

   - name: Create security group that allows SSH
     azure_rm_securitygroup:
       name: ansible-rhel-sg
       resource_group: ansible-rhel-rg
       rules:
         - name: SSH
           protocol: Tcp
           destination_port_range: 22
           access: Allow
           priority: 100
           direction: Inbound

   - name: Create NIC
     azure_rm_networkinterface:
       name: ansible-rhel-nic
       resource_group: ansible-rhel-rg
       virtual_network: ansible-rhel-vnet
       subnet: ansible-rhel-subnet
       public_ip_name: ansible-rhel-ip
       security_group: ansible-rhel-sg

   - name: Create virtual machine
     azure_rm_virtualmachine:
       name: RHEL8
       resource_group: ansible-rhel-rg
       vm_size: Standard_A1_V2
       admin_username: abi
       admin_password: Akshi@123
       network_interfaces: ansible-rhel-nic
       image:
         offer: "RHEL"
         publisher: "RedHat"
         sku: '8'
         version: latest
   - name: show IP
     debug:
       msg: " the ip is {{ ansible_rhel_ip.state.ip_address }} "
